In [11]:
# import pdfplumber
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords 
from string import punctuation
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
from nltk.probability import FreqDist
from heapq import nlargest
from collections import defaultdict
import pandas as pd 
from nltk.collocations import *
# nltk.download('punkt')
# nltk.download('stopwords')
# nltk.download('wordnet')

In [18]:
# Import CV
f=open('shubhi_shrotriya_resume_Deloitte.txt','r', errors = 'ignore')
text=f.read()

In [19]:
def nlp(x):
    word_sent = word_tokenize(x.lower().replace("\n",""))
    _stopwords = set(stopwords.words('english') + list(punctuation)+list("●")+list('–')+list('’'))
    word_sent=[word for word in word_sent if word not in _stopwords]
    lemmatizer = WordNetLemmatizer()
    NLP_Processed_CV = [lemmatizer.lemmatize(word) for word in word_tokenize(" ".join(word_sent))]
#     return " ".join(NLP_Processed_CV)
    return NLP_Processed_CV

In [20]:
def get_key_word(x):
    finder = BigramCollocationFinder.from_words(x)
    lst = []
    Key_word_from_CV = []
    for i in sorted(finder.ngram_fd.items()):
    # if a double word appears more than once, then print it out.
        if i[1] > 1:
            print(i)
            lst.append(i[0])
        else:
            pass

    # print("************************")
    for j in lst:
    #     print(" ".join(j))
        Key_word_from_CV.append(" ".join(j))
    return Key_word_from_CV

In [21]:
NLP_Processed_CV = nlp(text)
# NLP_Processed_CV=' '.join(NLP_Processed_CV)
NLP_Processed_CV

['shubhi',
 'shrotriyashubhishrotriya09',
 'gmail.comem22mtech14003',
 'iith.ac.in9068998298academic',
 'detailsyeardegreeinstitutecgpa/marks',
 '2024m.tech',
 'techno-entrepreneurshipiit',
 'hyderabad9.042021',
 'b.tech',
 'electronics',
 'communication',
 'engineeringzhcet',
 'amu8.212017xii',
 'amu',
 'sssg',
 'amu87.6',
 '2014x',
 'cbse',
 'olf89.3',
 'position',
 'responsibilitylinkedin',
 'page',
 'manager',
 'curated',
 'engaging',
 'informative',
 'departmental',
 'post',
 'blogs.team',
 'lead',
 'led',
 'team',
 'participate',
 'secure',
 'second',
 'runner',
 'national',
 'event',
 "createch'2020",
 'organized',
 'bylnt',
 'company.team',
 'lead',
 'led',
 '12-student',
 'team',
 'ideating',
 'designing',
 'fabricating',
 'hybrid',
 'tri-cycle',
 'national',
 'eventefficycle',
 'organized',
 'sae-nis',
 'eventually',
 'winning',
 "'futuristic",
 'efficycle',
 "award'2018.thesisstage",
 '1-',
 'conducting',
 'market',
 'research',
 'business',
 'hypothesis',
 'product',
 'rese

In [24]:
key_word = get_key_word(NLP_Processed_CV)
key_word


(('case', 'study'), 3)
(('lead', 'led'), 2)
(('literature', 'review'), 2)
(('market', 'research'), 2)


['case study', 'lead led', 'literature review', 'market research']

# Importing scapped df

In [25]:
DF_PATH = "data.csv"

In [26]:
df = pd.read_csv(DF_PATH)
df

company  \
0                           IBM   
1                           IBM   
2                           IBM   
3                           IBM   
4                           IBM   
...                         ...   
5497                         EY   
5498  JPMorgan Chase Bank, N.A.   
5499                  Accenture   
5500                        IBM   
5501                        IBM   

                                        positionName  \
0                         Application Developer: EAI   
1       Application Developer: IBM Cloud Integration   
2                                    Cloud Developer   
3         Application Developer: Microsoft Analytics   
4                      Software Developer: Microsoft   
...                                              ...   
5497               Java_Full_stack_Backend Developer   
5498     FRDC-RDT-Accounts- Java Developer-Hyderabad   
5499                   ASP.NET Application Developer   
5500  Application Developer: SAP NextGen UX & Mobile   
5501                                 Cloud Developer   

                                            description salary  \
0     \r\n \r\n  Introduction\r\n   As an Applicatio...    NaN   
1     \r\n \r\n  Introduction\r\n   As an Applicatio...    NaN   
2     \r\n \r\n  Introduction\r\n   At IBM, work is ...    NaN   
3     \r\n \r\n  Introduction\r\n   As an Applicatio...    NaN   
4     \r\n \r\n  Introduction\r\n   \r\n  \r\n   In ...    NaN   
...                                                 ...    ...   
5497  \r\n At EY, you’ll have the chance to build a ...    NaN   
5498  \r\n As a Software Engineer III at JPMorgan Ch...    NaN   
5499  \r\n About Accenture: Accenture is a global pr...    NaN   
5500  \r\n \r\n  Introduction\r\n   As an Applicatio...    NaN   
5501  \r\n \r\n  Introduction\r\n   At IBM, work is ...    NaN   

                    location  rating  reviewsCount   postedAt  \
0          Pune, Maharashtra     3.9       31981.0      Today   
1       Bengaluru, Karnataka     3.9       31981.0      Today   
2       Bengaluru, Karnataka     3.9       31981.0  1 day ago   
3       Hyderabad, Telangana     3.9       31981.0      Today   
4         Ahmedabad, Gujarat     3.9       31981.0  1 day ago   
...                      ...     ...           ...        ...   
5497    Bengaluru, Karnataka     3.9        8726.0  1 day ago   
5498    Hyderabad, Telangana     3.9       18023.0  1 day ago   
5499  Coimbatore, Tamil Nadu     4.0       23070.0  1 day ago   
5500    Bengaluru, Karnataka     3.9       31981.0  1 day ago   
5501    Bengaluru, Karnataka     3.9       31981.0  1 day ago   

                                      externalApplyLink  \
0     https://in.indeed.com/applystart?jk=fb3f055a63...   
1     https://in.indeed.com/applystart?jk=dcbc5cf465...   
2     https://in.indeed.com/applystart?jk=6bc552083f...   
3     https://in.indeed.com/applystart?jk=bf6cebfb33...   
4     https://in.indeed.com/applystart?jk=b1b335e8ad...   
...                                                 ...   
5497  https://in.indeed.com/applystart?jk=3a51e284cd...   
5498  https://in.indeed.com/applystart?jk=dd7e7fdfbe...   
5499  https://in.indeed.com/applystart?jk=ef3761755f...   
5500  https://in.indeed.com/applystart?jk=1e1e79f155...   
5501  https://in.indeed.com/applystart?jk=6bc552083f...   

                                                    url  
0     https://www.indeed.co.in/rc/clk?jk=fb3f055a632...  
1     https://www.indeed.co.in/rc/clk?jk=dcbc5cf4654...  
2     https://www.indeed.co.in/rc/clk?jk=6bc552083f9...  
3     https://www.indeed.co.in/rc/clk?jk=bf6cebfb333...  
4     https://www.indeed.co.in/rc/clk?jk=b1b335e8ad3...  
...                                                 ...  
5497  https://www.indeed.co.in/rc/clk?jk=3a51e284cd8...  
5498  https://www.indeed.co.in/rc/clk?jk=dd7e7fdfbe7...  
5499  https://www.indeed.co.in/rc/clk?jk=ef3761755fa...  
5500  https://www.indeed.co.in/rc/clk?jk=1e1e79f1550...  
5501  htt

In [27]:
df["JobID"]=df.index

In [28]:
df

company  \
0                           IBM   
1                           IBM   
2                           IBM   
3                           IBM   
4                           IBM   
...                         ...   
5497                         EY   
5498  JPMorgan Chase Bank, N.A.   
5499                  Accenture   
5500                        IBM   
5501                        IBM   

                                        positionName  \
0                         Application Developer: EAI   
1       Application Developer: IBM Cloud Integration   
2                                    Cloud Developer   
3         Application Developer: Microsoft Analytics   
4                      Software Developer: Microsoft   
...                                              ...   
5497               Java_Full_stack_Backend Developer   
5498     FRDC-RDT-Accounts- Java Developer-Hyderabad   
5499                   ASP.NET Application Developer   
5500  Application Developer: SAP NextGen UX & Mobile   
5501                                 Cloud Developer   

                                            description salary  \
0     \r\n \r\n  Introduction\r\n   As an Applicatio...    NaN   
1     \r\n \r\n  Introduction\r\n   As an Applicatio...    NaN   
2     \r\n \r\n  Introduction\r\n   At IBM, work is ...    NaN   
3     \r\n \r\n  Introduction\r\n   As an Applicatio...    NaN   
4     \r\n \r\n  Introduction\r\n   \r\n  \r\n   In ...    NaN   
...                                                 ...    ...   
5497  \r\n At EY, you’ll have the chance to build a ...    NaN   
5498  \r\n As a Software Engineer III at JPMorgan Ch...    NaN   
5499  \r\n About Accenture: Accenture is a global pr...    NaN   
5500  \r\n \r\n  Introduction\r\n   As an Applicatio...    NaN   
5501  \r\n \r\n  Introduction\r\n   At IBM, work is ...    NaN   

                    location  rating  reviewsCount   postedAt  \
0          Pune, Maharashtra     3.9       31981.0      Today   
1       Bengaluru, Karnataka     3.9       31981.0      Today   
2       Bengaluru, Karnataka     3.9       31981.0  1 day ago   
3       Hyderabad, Telangana     3.9       31981.0      Today   
4         Ahmedabad, Gujarat     3.9       31981.0  1 day ago   
...                      ...     ...           ...        ...   
5497    Bengaluru, Karnataka     3.9        8726.0  1 day ago   
5498    Hyderabad, Telangana     3.9       18023.0  1 day ago   
5499  Coimbatore, Tamil Nadu     4.0       23070.0  1 day ago   
5500    Bengaluru, Karnataka     3.9       31981.0  1 day ago   
5501    Bengaluru, Karnataka     3.9       31981.0  1 day ago   

                                      externalApplyLink  \
0     https://in.indeed.com/applystart?jk=fb3f055a63...   
1     https://in.indeed.com/applystart?jk=dcbc5cf465...   
2     https://in.indeed.com/applystart?jk=6bc552083f...   
3     https://in.indeed.com/applystart?jk=bf6cebfb33...   
4     https://in.indeed.com/applystart?jk=b1b335e8ad...   
...                                                 ...   
5497  https://in.indeed.com/applystart?jk=3a51e284cd...   
5498  https://in.indeed.com/applystart?jk=dd7e7fdfbe...   
5499  https://in.indeed.com/applystart?jk=ef3761755f...   
5500  https://in.indeed.com/applystart?jk=1e1e79f155...   
5501  https://in.indeed.com/applystart?jk=6bc552083f...   

                                                    url  JobID  
0     https://www.indeed.co.in/rc/clk?jk=fb3f055a632...      0  
1     https://www.indeed.co.in/rc/clk?jk=dcbc5cf4654...      1  
2     https://www.indeed.co.in/rc/clk?jk=6bc552083f9...      2  
3     https://www.indeed.co.in/rc/clk?jk=bf6cebfb333...      3  
4     https://www.indeed.co.in/rc/clk?jk=b1b335e8ad3...      4  
...                                                 ...    ...  
5497  https://www.indeed.co.in/rc/clk?jk=3a51e284cd8...   5497  
5498  https://www.indeed.co.in/rc/clk?jk=dd7e7fdfbe7...   5498  
5499  https://www.indeed.co.in/rc/clk?jk=ef3761755fa...   5499

In [29]:
df.shape


(5502, 11)

In [30]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5502 entries, 0 to 5501
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   company            5408 non-null   object 
 1   positionName       5502 non-null   object 
 2   description        5502 non-null   object 
 3   salary             1248 non-null   object 
 4   location           5502 non-null   object 
 5   rating             3128 non-null   float64
 6   reviewsCount       3128 non-null   float64
 7   postedAt           5502 non-null   object 
 8   externalApplyLink  4044 non-null   object 
 9   url                5502 non-null   object 
 10  JobID              5502 non-null   int64  
dtypes: float64(2), int64(1), object(8)
memory usage: 473.0+ KB


In [31]:
df['All'] = df[df.columns[0:]].apply(
    lambda x: ','.join(x.dropna().astype(str)),
    axis=1
)

In [32]:
df

company  \
0                           IBM   
1                           IBM   
2                           IBM   
3                           IBM   
4                           IBM   
...                         ...   
5497                         EY   
5498  JPMorgan Chase Bank, N.A.   
5499                  Accenture   
5500                        IBM   
5501                        IBM   

                                        positionName  \
0                         Application Developer: EAI   
1       Application Developer: IBM Cloud Integration   
2                                    Cloud Developer   
3         Application Developer: Microsoft Analytics   
4                      Software Developer: Microsoft   
...                                              ...   
5497               Java_Full_stack_Backend Developer   
5498     FRDC-RDT-Accounts- Java Developer-Hyderabad   
5499                   ASP.NET Application Developer   
5500  Application Developer: SAP NextGen UX & Mobile   
5501                                 Cloud Developer   

                                            description salary  \
0     \r\n \r\n  Introduction\r\n   As an Applicatio...    NaN   
1     \r\n \r\n  Introduction\r\n   As an Applicatio...    NaN   
2     \r\n \r\n  Introduction\r\n   At IBM, work is ...    NaN   
3     \r\n \r\n  Introduction\r\n   As an Applicatio...    NaN   
4     \r\n \r\n  Introduction\r\n   \r\n  \r\n   In ...    NaN   
...                                                 ...    ...   
5497  \r\n At EY, you’ll have the chance to build a ...    NaN   
5498  \r\n As a Software Engineer III at JPMorgan Ch...    NaN   
5499  \r\n About Accenture: Accenture is a global pr...    NaN   
5500  \r\n \r\n  Introduction\r\n   As an Applicatio...    NaN   
5501  \r\n \r\n  Introduction\r\n   At IBM, work is ...    NaN   

                    location  rating  reviewsCount   postedAt  \
0          Pune, Maharashtra     3.9       31981.0      Today   
1       Bengaluru, Karnataka     3.9       31981.0      Today   
2       Bengaluru, Karnataka     3.9       31981.0  1 day ago   
3       Hyderabad, Telangana     3.9       31981.0      Today   
4         Ahmedabad, Gujarat     3.9       31981.0  1 day ago   
...                      ...     ...           ...        ...   
5497    Bengaluru, Karnataka     3.9        8726.0  1 day ago   
5498    Hyderabad, Telangana     3.9       18023.0  1 day ago   
5499  Coimbatore, Tamil Nadu     4.0       23070.0  1 day ago   
5500    Bengaluru, Karnataka     3.9       31981.0  1 day ago   
5501    Bengaluru, Karnataka     3.9       31981.0  1 day ago   

                                      externalApplyLink  \
0     https://in.indeed.com/applystart?jk=fb3f055a63...   
1     https://in.indeed.com/applystart?jk=dcbc5cf465...   
2     https://in.indeed.com/applystart?jk=6bc552083f...   
3     https://in.indeed.com/applystart?jk=bf6cebfb33...   
4     https://in.indeed.com/applystart?jk=b1b335e8ad...   
...                                                 ...   
5497  https://in.indeed.com/applystart?jk=3a51e284cd...   
5498  https://in.indeed.com/applystart?jk=dd7e7fdfbe...   
5499  https://in.indeed.com/applystart?jk=ef3761755f...   
5500  https://in.indeed.com/applystart?jk=1e1e79f155...   
5501  https://in.indeed.com/applystart?jk=6bc552083f...   

                                                    url  JobID  \
0     https://www.indeed.co.in/rc/clk?jk=fb3f055a632...      0   
1     https://www.indeed.co.in/rc/clk?jk=dcbc5cf4654...      1   
2     https://www.indeed.co.in/rc/clk?jk=6bc552083f9...      2   
3     https://www.indeed.co.in/rc/clk?jk=bf6cebfb333...      3   
4     https://www.indeed.co.in/rc/clk?jk=b1b335e8ad3...      4   
...                                                 ...    ...   
5497  https://www.indeed.co.in/rc/clk?jk=3a51e284cd8...   5497   
5498  https://www.indeed.co.in/rc/clk?jk=dd7e7fdfbe7...   5498   
5499  https://www.indeed.co.in/rc/clk?jk=ef3761755fa.

In [33]:
df['All']

0       IBM,Application Developer: EAI,\r\n \r\n  Intr...
1       IBM,Application Developer: IBM Cloud Integrati...
2       IBM,Cloud Developer,\r\n \r\n  Introduction\r\...
3       IBM,Application Developer: Microsoft Analytics...
4       IBM,Software Developer: Microsoft,\r\n \r\n  I...
                              ...                        
5497    EY,Java_Full_stack_Backend Developer,\r\n At E...
5498    JPMorgan Chase Bank, N.A.,FRDC-RDT-Accounts- J...
5499    Accenture,ASP.NET Application Developer,\r\n A...
5500    IBM,Application Developer: SAP NextGen UX & Mo...
5501    IBM,Cloud Developer,\r\n \r\n  Introduction\r\...
Name: All, Length: 5502, dtype: object

In [34]:
df["description"].replace(r'\n','', regex=True,inplace=True)
df["description"].replace(r'\r','', regex=True,inplace=True)  
df = df.replace(' ', '')
df.description = df.description.str.strip()
df.All = df.All.str.strip()

In [35]:
df

company  \
0                           IBM   
1                           IBM   
2                           IBM   
3                           IBM   
4                           IBM   
...                         ...   
5497                         EY   
5498  JPMorgan Chase Bank, N.A.   
5499                  Accenture   
5500                        IBM   
5501                        IBM   

                                        positionName  \
0                         Application Developer: EAI   
1       Application Developer: IBM Cloud Integration   
2                                    Cloud Developer   
3         Application Developer: Microsoft Analytics   
4                      Software Developer: Microsoft   
...                                              ...   
5497               Java_Full_stack_Backend Developer   
5498     FRDC-RDT-Accounts- Java Developer-Hyderabad   
5499                   ASP.NET Application Developer   
5500  Application Developer: SAP NextGen UX & Mobile   
5501                                 Cloud Developer   

                                            description salary  \
0     Introduction   As an Application Developer, yo...    NaN   
1     Introduction   As an Application Developer, yo...    NaN   
2     Introduction   At IBM, work is more than a job...    NaN   
3     Introduction   As an Application Developer, yo...    NaN   
4     Introduction        In this role, you'll work ...    NaN   
...                                                 ...    ...   
5497  At EY, you’ll have the chance to build a caree...    NaN   
5498  As a Software Engineer III at JPMorgan Chase, ...    NaN   
5499  About Accenture: Accenture is a global profess...    NaN   
5500  Introduction   As an Application Developer, yo...    NaN   
5501  Introduction   At IBM, work is more than a job...    NaN   

                    location  rating  reviewsCount   postedAt  \
0          Pune, Maharashtra     3.9       31981.0      Today   
1       Bengaluru, Karnataka     3.9       31981.0      Today   
2       Bengaluru, Karnataka     3.9       31981.0  1 day ago   
3       Hyderabad, Telangana     3.9       31981.0      Today   
4         Ahmedabad, Gujarat     3.9       31981.0  1 day ago   
...                      ...     ...           ...        ...   
5497    Bengaluru, Karnataka     3.9        8726.0  1 day ago   
5498    Hyderabad, Telangana     3.9       18023.0  1 day ago   
5499  Coimbatore, Tamil Nadu     4.0       23070.0  1 day ago   
5500    Bengaluru, Karnataka     3.9       31981.0  1 day ago   
5501    Bengaluru, Karnataka     3.9       31981.0  1 day ago   

                                      externalApplyLink  \
0     https://in.indeed.com/applystart?jk=fb3f055a63...   
1     https://in.indeed.com/applystart?jk=dcbc5cf465...   
2     https://in.indeed.com/applystart?jk=6bc552083f...   
3     https://in.indeed.com/applystart?jk=bf6cebfb33...   
4     https://in.indeed.com/applystart?jk=b1b335e8ad...   
...                                                 ...   
5497  https://in.indeed.com/applystart?jk=3a51e284cd...   
5498  https://in.indeed.com/applystart?jk=dd7e7fdfbe...   
5499  https://in.indeed.com/applystart?jk=ef3761755f...   
5500  https://in.indeed.com/applystart?jk=1e1e79f155...   
5501  https://in.indeed.com/applystart?jk=6bc552083f...   

                                                    url  JobID  \
0     https://www.indeed.co.in/rc/clk?jk=fb3f055a632...      0   
1     https://www.indeed.co.in/rc/clk?jk=dcbc5cf4654...      1   
2     https://www.indeed.co.in/rc/clk?jk=6bc552083f9...      2   
3     https://www.indeed.co.in/rc/clk?jk=bf6cebfb333...      3   
4     https://www.indeed.co.in/rc/clk?jk=b1b335e8ad3...      4   
...                                                 ...    ...   
5497  https://www.indeed.co.in/rc/clk?jk=3a51e284cd8...   5497   
5498  https://www.indeed.co.in/rc/clk?jk=dd7e7fdfbe7...   5498   
5499  https://www.indeed.co.in/rc/clk?jk=ef3761755fa.

# Put keywords of the CV into a dataframe

In [36]:
df2 = pd.DataFrame()
# append columns to an empty DataFrame
df2['title'] = ["I"]
df2['job highlights'] = ["I"]
df2['job description'] = ["I"]
df2['company overview'] = ["I"]
df2['industry'] = ["I"]

# Compare with the key words from CV only
df2['All'] = " ".join(key_word)

In [37]:
df2

title job highlights job description company overview industry  \
0     I              I               I                I        I   

                                                 All  
0  case study lead led literature review market r...

In [38]:
df.columns

Index(['company', 'positionName', 'description', 'salary', 'location',
       'rating', 'reviewsCount', 'postedAt', 'externalApplyLink', 'url',
       'JobID', 'All'],
      dtype='object')

# Recomendation Function

#klnsdsd

In [39]:
def get_recommendation(top, df_all, scores):
    recommendation = pd.DataFrame(columns = ['positionName', 'company',"location",'JobID','description','score'])
    count = 0
    for i in top:
#         recommendation.at[count, 'ApplicantID'] = u
        
        recommendation.at[count, 'positionName'] = df['positionName'][i]
        recommendation.at[count, 'company'] = df['company'][i]
        recommendation.at[count, 'location'] = df['location'][i]
    
        recommendation.at[count, 'JobID'] = df.index[i]
        recommendation.at[count, 'description'] = df['description'][i]
        recommendation.at[count, 'score'] =  scores[count]
        count += 1
    return recommendation

## cosine_similarity + TfidfVectorizer function

In [41]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer


def TFIDF(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    # TF-IDF Scraped data
    tfidf_jobid = tfidf_vectorizer.fit_transform(scraped_data)

    # TF-IDF CV
    user_tfidf = tfidf_vectorizer.transform(cv)

    # Using cosine_similarity on (Scraped data) & (CV)
    cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)

    output2 = list(cos_similarity_tfidf)
    return output2
    
output2 = TFIDF(df['All'], df2['All'])


In [42]:
len(output2)

5502

In [43]:
output2


[array([[0.03496333]]),
 array([[0.03421068]]),
 array([[0.04100105]]),
 array([[0.03847938]]),
 array([[0.04040894]]),
 array([[0.01180725]]),
 array([[0.04268917]]),
 array([[0.04364049]]),
 array([[0.0357396]]),
 array([[0.02723421]]),
 array([[0.03160473]]),
 array([[0.03575262]]),
 array([[0.03203653]]),
 array([[0.03668896]]),
 array([[0.03462295]]),
 array([[0.0359217]]),
 array([[0.02876143]]),
 array([[0.03116561]]),
 array([[0.03843969]]),
 array([[0.04244237]]),
 array([[0.0335724]]),
 array([[0.03488495]]),
 array([[0.0380524]]),
 array([[0.]]),
 array([[0.04019534]]),
 array([[0.]]),
 array([[0.03948246]]),
 array([[0.0240089]]),
 array([[0.04329296]]),
 array([[0.02596272]]),
 array([[0.03656386]]),
 array([[0.03092921]]),
 array([[0.04431681]]),
 array([[0.0363903]]),
 array([[0.]]),
 array([[0.02394287]]),
 array([[0.]]),
 array([[0.04545278]]),
 array([[0.03748139]]),
 array([[0.]]),
 array([[0.03708354]]),
 array([[0.03567444]]),
 array([[0.04253901]]),
 array([[0.]])

In [44]:
top = sorted(range(len(output2)), key=lambda i: output2[i], reverse=True)[:100]
list_scores = [output2[i][0][0] for i in top]
TF=get_recommendation(top,df, list_scores)
TF

positionName  \
0                                    Research Analyst   
1     Senior Associate - Pune - Technology Consulting   
2                            Insight Research Analyst   
3   Market Research Analyst – Cybersecurity and In...   
4                         Advisory_Cyber R&R_TPRM_BLR   
..                                                ...   
95    Director Engineering Blockchain & Digital Asset   
96                                    Product Manager   
97      Assistant Vice President (Business Analytics)   
98                               SOC Security Analyst   
99        Quantitative Investment Analytics-Associate   

                      company              location JobID  \
0             Aon Corporation  Bengaluru, Karnataka  1804   
1                         PwC     Pune, Maharashtra  4749   
2           forstaffing india      Gurgaon, Haryana  4285   
3                     Canalys  Bengaluru, Karnataka  1393   
4                         PwC  Bengaluru, Karnataka  1488   
..                        ...                   ...   ...   
95                 Mastercard     Pune, Maharashtra   259   
96                        IBM  Bengaluru, Karnataka   211   
97                       Citi  Bengaluru, Karnataka  2759   
98          Cameo Global, Inc  Bengaluru, Karnataka  1072   
99  JPMorgan Chase Bank, N.A.   Mumbai, Maharashtra  2633   

                                          description     score  
0   Posting Description:            Job Informatio...  0.128151  
1   Line of Service Advisory   Industry/Sector Not...  0.118448  
2   Description    DESCRIPTION       About the com...  0.117138  
3   Canalys is looking for a Market Research Analy...  0.102206  
4   Line of Service Advisory   Industry/Sector Not...  0.099281  
..                                                ...       ...  
95  Our Purpose      We work to connect and power ...  0.046916  
96  Introduction   Software Developers at IBM are ...  0.046915  
97  Role Outline  The role of AVP – Strategic Busi...  0.046581  
98  Security Analyst (Level 1) Perform security mo...  0.046491  
99  You are a strategic thinker passionate about d...  0.046339  

[100 rows x 6 columns]

## cosine_similarity + CountVectorizer

In [45]:

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

count_vectorizer = CountVectorizer()
count_jobid = count_vectorizer.fit_transform(df['All']) #converting job data into vectors using count vectorizers
count_jobid

<5502x49785 sparse matrix of type '<class 'numpy.int64'>'
	with 1658284 stored elements in Compressed Sparse Row format>

In [46]:
# print(count_jobid)


In [47]:
user_count = count_vectorizer.transform(df2['All'])#converting user cv data into vectors using count vectorizers
user_count

<1x49785 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [48]:
print(user_count)


  (0, 23537)	1
  (0, 36147)	1
  (0, 36200)	1
  (0, 36449)	1
  (0, 37036)	1
  (0, 42852)	1
  (0, 43080)	1
  (0, 45634)	1


In [49]:
cos_similarity_countv = map(lambda x: cosine_similarity(user_count, x),count_jobid)
output3 = list(cos_similarity_countv)
#output3

In [50]:
output3

[array([[0.0205518]]),
 array([[0.02053158]]),
 array([[0.02164155]]),
 array([[0.02006341]]),
 array([[0.01730694]]),
 array([[0.01109924]]),
 array([[0.02284654]]),
 array([[0.02034334]]),
 array([[0.01815007]]),
 array([[0.01269641]]),
 array([[0.01940026]]),
 array([[0.01793716]]),
 array([[0.01416766]]),
 array([[0.01829745]]),
 array([[0.02129528]]),
 array([[0.01804502]]),
 array([[0.0127791]]),
 array([[0.01356876]]),
 array([[0.01861426]]),
 array([[0.01930317]]),
 array([[0.01392587]]),
 array([[0.01613609]]),
 array([[0.01821086]]),
 array([[0.]]),
 array([[0.02156308]]),
 array([[0.]]),
 array([[0.01726315]]),
 array([[0.02628602]]),
 array([[0.02298328]]),
 array([[0.03887916]]),
 array([[0.01636488]]),
 array([[0.01368067]]),
 array([[0.01671054]]),
 array([[0.01862149]]),
 array([[0.]]),
 array([[0.00951581]]),
 array([[0.]]),
 array([[0.02409347]]),
 array([[0.01982456]]),
 array([[0.]]),
 array([[0.02261786]]),
 array([[0.01804784]]),
 array([[0.02162812]]),
 array([[0

In [51]:
df.rating

0       3.9
1       3.9
2       3.9
3       3.9
4       3.9
       ... 
5497    3.9
5498    3.9
5499    4.0
5500    3.9
5501    3.9
Name: rating, Length: 5502, dtype: float64

In [52]:
top = sorted(range(len(output3)), key=lambda i: output3[i], reverse=True)[:100]
list_scores = [output3[i][0][0] for i in top]
cv=get_recommendation(top, df, list_scores)
cv

positionName  \
0                                    Research Analyst   
1                            Insight Research Analyst   
2   Market Research Analyst – Cybersecurity and In...   
3                             Lead Frontend Developer   
4                             Lead Frontend Developer   
..                                                ...   
95               Clinical Programmer II - (ePRO/eCOA)   
96                             Magento Technical Lead   
97                        Advisory_Cyber R&R_TPRM_BLR   
98                              Application Architect   
99                             Digital Analytics-Lead   

                          company              location JobID  \
0                 Aon Corporation  Bengaluru, Karnataka  1804   
1               forstaffing india      Gurgaon, Haryana  4285   
2                         Canalys  Bengaluru, Karnataka  1393   
3                        BigShyft  Bengaluru, Karnataka  3082   
4                        BigShyft  Bengaluru, Karnataka  4872   
..                            ...                   ...   ...   
95         Syneos Health Clinical     Pune, Maharashtra  4674   
96                     BORN Group                 India   671   
97                            PwC  Bengaluru, Karnataka  1488   
98                  Wipro Limited  Hyderabad, Telangana    46   
99  MNR Solutions Private Limited  Bengaluru, Karnataka  2978   

                                          description     score  
0   Posting Description:            Job Informatio...  0.112552  
1   Description    DESCRIPTION       About the com...     0.105  
2   Canalys is looking for a Market Research Analy...  0.095345  
3   What makes you a great fit:            Good pr...  0.094967  
4   What makes you a great fit:            Good pr...  0.094967  
..                                                ...       ...  
95  Description  Clinical Programmer II (eCOA/ePRO...   0.04226  
96  IN - Remote                 India             ...  0.042083  
97  Line of Service Advisory   Industry/Sector Not...    0.0415  
98  Overview:   Role Purpose  The purpose of the r...  0.041431  
99  Job Description:Objective:eB2B Program is the ...  0.041386  

[100 rows x 6 columns]

In [53]:
cv.description[1]

'Description    DESCRIPTION       About the company:     Location: - Gurgaon     Team Strength: 300+ people.     About the Company: We are a team of analysts, engineers, data scientists, and designers building powerful intelligence tools for business users. Company is a 360-degree market intelligence platform that enables businesses to monitor competitors, customers, suppliers, and critical market variables against event trigger on an ongoing basis with unmatched precision and relevance. The product team at Company is responsible for defining the enhancements and new features around the various aspects of our flagship product. This involves feature additions to our flagship platform, performance/architecture enhancements, tuning our NLP, improvements in our sourcing engine, machine learning algorithms, and much more. We stay on the cutting edge while being sensible about it.            About the position: Designation: InSight Research Analyst     Experience required- 3-5 years     Repo

## TfidfVectorizer + NearestNeighbors

In [54]:
from sklearn.neighbors import NearestNeighbors

def KNN(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    
    KNN = NearestNeighbors(n_neighbors=100,p=2)
    KNN.fit(tfidf_vectorizer.fit_transform(scraped_data))
#     NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv), return_distance=True)
    NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv))
    top = NNs[1][0][1:]
    index_score = NNs[0][0][1:]

    knn = get_recommendation(top, df, index_score)
    return knn

knn = KNN(df['All'], df2['All'])
knn

positionName  \
0     Senior Associate - Pune - Technology Consulting   
1                            Insight Research Analyst   
2   Market Research Analyst – Cybersecurity and In...   
3                         Advisory_Cyber R&R_TPRM_BLR   
4               Sr Clinical Programmer (SAS Listings)   
..                                                ...   
94    Director Engineering Blockchain & Digital Asset   
95                                    Product Manager   
96      Assistant Vice President (Business Analytics)   
97                               SOC Security Analyst   
98        Quantitative Investment Analytics-Associate   

                      company              location JobID  \
0                         PwC     Pune, Maharashtra  4749   
1           forstaffing india      Gurgaon, Haryana  4285   
2                     Canalys  Bengaluru, Karnataka  1393   
3                         PwC  Bengaluru, Karnataka  1488   
4      Syneos Health Clinical                Remote  1699   
..                        ...                   ...   ...   
94                 Mastercard     Pune, Maharashtra   259   
95                        IBM  Bengaluru, Karnataka   211   
96                       Citi  Bengaluru, Karnataka  2759   
97          Cameo Global, Inc  Bengaluru, Karnataka  1072   
98  JPMorgan Chase Bank, N.A.   Mumbai, Maharashtra  2633   

                                          description     score  
0   Line of Service Advisory   Industry/Sector Not...   1.32782  
1   Description    DESCRIPTION       About the com...  1.328806  
2   Canalys is looking for a Market Research Analy...  1.339996  
3   Line of Service Advisory   Industry/Sector Not...  1.342176  
4   Description  Senior Clinical Programmer (SAS L...  1.346427  
..                                                ...       ...  
94  Our Purpose      We work to connect and power ...   1.38064  
95  Introduction   Software Developers at IBM are ...  1.380641  
96  Role Outline  The role of AVP – Strategic Busi...  1.380883  
97  Security Analyst (Level 1) Perform security mo...  1.380948  
98  You are a strategic thinker passionate about d...  1.381058  

[99 rows x 6 columns]

In [55]:

knn.to_csv('knn.csv', index=False)

In [56]:
cv

positionName  \
0                                    Research Analyst   
1                            Insight Research Analyst   
2   Market Research Analyst – Cybersecurity and In...   
3                             Lead Frontend Developer   
4                             Lead Frontend Developer   
..                                                ...   
95               Clinical Programmer II - (ePRO/eCOA)   
96                             Magento Technical Lead   
97                        Advisory_Cyber R&R_TPRM_BLR   
98                              Application Architect   
99                             Digital Analytics-Lead   

                          company              location JobID  \
0                 Aon Corporation  Bengaluru, Karnataka  1804   
1               forstaffing india      Gurgaon, Haryana  4285   
2                         Canalys  Bengaluru, Karnataka  1393   
3                        BigShyft  Bengaluru, Karnataka  3082   
4                        BigShyft  Bengaluru, Karnataka  4872   
..                            ...                   ...   ...   
95         Syneos Health Clinical     Pune, Maharashtra  4674   
96                     BORN Group                 India   671   
97                            PwC  Bengaluru, Karnataka  1488   
98                  Wipro Limited  Hyderabad, Telangana    46   
99  MNR Solutions Private Limited  Bengaluru, Karnataka  2978   

                                          description     score  
0   Posting Description:            Job Informatio...  0.112552  
1   Description    DESCRIPTION       About the com...     0.105  
2   Canalys is looking for a Market Research Analy...  0.095345  
3   What makes you a great fit:            Good pr...  0.094967  
4   What makes you a great fit:            Good pr...  0.094967  
..                                                ...       ...  
95  Description  Clinical Programmer II (eCOA/ePRO...   0.04226  
96  IN - Remote                 India             ...  0.042083  
97  Line of Service Advisory   Industry/Sector Not...    0.0415  
98  Overview:   Role Purpose  The purpose of the r...  0.041431  
99  Job Description:Objective:eB2B Program is the ...  0.041386  

[100 rows x 6 columns]

## Combined TFIDF, CV and KNN result together, to make a dataframe "final"


In [57]:
merge1 = knn[['JobID','positionName', 'score']].merge(TF[['JobID','score']], on= "JobID")

In [59]:
# merge1 = knn[['JobID','title', 'score']].merge(TF[['JobID','score']], on= "JobID")
# final = merge1.merge(cv[['JobID','score']], on = "JobID")
# final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
# final.head()a

final = merge1.merge(cv[['JobID','score']], on = "JobID")
final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
final.head()

JobID                                       positionName       KNN  \
0  4749    Senior Associate - Pune - Technology Consulting   1.32782   
1  4285                           Insight Research Analyst  1.328806   
2  1393  Market Research Analyst – Cybersecurity and In...  1.339996   
3  1488                        Advisory_Cyber R&R_TPRM_BLR  1.342176   
4  4674               Clinical Programmer II - (ePRO/eCOA)  1.349381   

     TF-IDF        CV  
0  0.118448   0.04605  
1  0.117138     0.105  
2  0.102206  0.095345  
3  0.099281    0.0415  
4  0.089585   0.04226

In [58]:
final

NameError: name 'final' is not defined

In [60]:
# Scale it
from sklearn.preprocessing import MinMaxScaler
slr = MinMaxScaler()
final[["KNN", "TF-IDF", 'CV']] = slr.fit_transform(final[["KNN", "TF-IDF", 'CV']])

# Multiply by weights
final['KNN'] = (1-final['KNN'])/3
final['TF-IDF'] = final['TF-IDF']/3
final['CV'] = final['CV']/3
final['Final'] = final['KNN']+final['TF-IDF']+final['CV']
final.sort_values(by="Final", ascending=False)

JobID                                       positionName       KNN  \
1   4285                           Insight Research Analyst  0.327140   
2   1393  Market Research Analyst – Cybersecurity and In...  0.256845   
0   4749    Senior Associate - Pune - Technology Consulting  0.333333   
6   4632                         Sales Manager - Auto Loans  0.165718   
7   4702                 Marketing Manager Bangalore Market  0.165653   
3   1488                        Advisory_Cyber R&R_TPRM_BLR  0.243147   
5   2906  People Analytics Research & Thought Leadership...  0.178746   
12  3082                            Lead Frontend Developer  0.088072   
13  5362                            Lead Frontend Developer  0.088017   
14  4872                            Lead Frontend Developer  0.087882   
4   4674               Clinical Programmer II - (ePRO/eCOA)  0.197886   
15  4694      Asst. Manager/ Deputy Manager – Plug & Socket  0.084625   
9   1697                              API Automation Tester  0.107586   
10  1920  JOB OPENING FOR PERSON WITH DISABILITIES IN CO...  0.098229   
8   4686                              Clinical Statistician  0.144892   
24  1765  Research Analyst II - EO/IR & Radar Systems (H...  0.064033   
11   881            Tech Manager, Cloud operations Engineer  0.096382   
19  1814                                             Intern  0.076402   
32  1020  Content writing and market research – Cyber Se...  0.040035   
21  5144               Lead Business Intelligence Developer  0.064899   
22  1531               Lead Business Intelligence Developer  0.064848   
23  3056               Lead Business Intelligence Developer  0.064818   
29  3967                           Team Lead - HR Associate  0.050295   
16  1554  Know Your Customer - Client Data Analyst - Tea...  0.083907   
17  4755  Know Your Customer - Client Data Analyst - Tea...  0.083688   
20   866        Architect I - Cloud Infrastructure Services  0.070079   
30  4116                         Technical Research Analyst  0.048419   
31  4968                 Territory Manager - Mortgage Sales  0.045361   
18    46                              Application Architect  0.082164   
27  4812                                Sales Manager- Clix  0.051447   
43  2464                    Lead Java Developer with Python  0.004507   
44  4806                     Business Development Executive  0.003976   
36  4791          Product Manager – Sales for Lab Equipment  0.032943   
25  3344                     Lead II - Software Engineering  0.062703   
26  1629              Risk Modelling & Analytics Specialist  0.057010   
34  4654                        Product Marketing Associate  0.036534   
35  1656                        Product Marketing Associate  0.036504   
41  1313             Lead Cyber Security- Database Security  0.008848   
33  2876                               Data Science Trainer  0.039902   
28   432                        Associate Product Manager I  0.050956   
37   117                                     Technical Lead  0.029999   
38  4849                              Senior Product Design  0.026010   
39    97                                    Blockchain Lead  0.020473   
40  2567  India Market Unit - Data Science - Utilities -...  0.013028   
42  1847  Technical Research Analyst (Offshore Field Dev...  0.007876   
45  2759      Assistant Vice President (Business Analytics)  0.000000   

      TF-IDF        CV     Final  
1   0.327259  0.333333  0.987731  
2   0.257999  0.282702  0.797545  
0   0.333333  0.024221  0.690887  
6   0.167350  0.258462  0.591529  
7   0.167286  0.167685  0.500624  
3   0.244435  0.000359  0.487941  
5   0.180370  0.121419  0.480535  
12  0.089341  0.280722  0.458135  
13  0.089286  0.280722  0.458025  
14  0.089150  0.280722  0.457754  
4   0.199462  0.004346  0.401694  
15  0.085862  0.221714  0.392202  
9   0.109014  0.129100  0.345699  
10  0.099586  0.120686  0.318501  
8   0.146497  0.009136  0.300525  
24  0.06504

In [61]:
# final.to_csv('final.csv', index=False)
final2 = final.sort_values(by="Final", ascending=False).copy()
final2

JobID                                       positionName       KNN  \
1   4285                           Insight Research Analyst  0.327140   
2   1393  Market Research Analyst – Cybersecurity and In...  0.256845   
0   4749    Senior Associate - Pune - Technology Consulting  0.333333   
6   4632                         Sales Manager - Auto Loans  0.165718   
7   4702                 Marketing Manager Bangalore Market  0.165653   
3   1488                        Advisory_Cyber R&R_TPRM_BLR  0.243147   
5   2906  People Analytics Research & Thought Leadership...  0.178746   
12  3082                            Lead Frontend Developer  0.088072   
13  5362                            Lead Frontend Developer  0.088017   
14  4872                            Lead Frontend Developer  0.087882   
4   4674               Clinical Programmer II - (ePRO/eCOA)  0.197886   
15  4694      Asst. Manager/ Deputy Manager – Plug & Socket  0.084625   
9   1697                              API Automation Tester  0.107586   
10  1920  JOB OPENING FOR PERSON WITH DISABILITIES IN CO...  0.098229   
8   4686                              Clinical Statistician  0.144892   
24  1765  Research Analyst II - EO/IR & Radar Systems (H...  0.064033   
11   881            Tech Manager, Cloud operations Engineer  0.096382   
19  1814                                             Intern  0.076402   
32  1020  Content writing and market research – Cyber Se...  0.040035   
21  5144               Lead Business Intelligence Developer  0.064899   
22  1531               Lead Business Intelligence Developer  0.064848   
23  3056               Lead Business Intelligence Developer  0.064818   
29  3967                           Team Lead - HR Associate  0.050295   
16  1554  Know Your Customer - Client Data Analyst - Tea...  0.083907   
17  4755  Know Your Customer - Client Data Analyst - Tea...  0.083688   
20   866        Architect I - Cloud Infrastructure Services  0.070079   
30  4116                         Technical Research Analyst  0.048419   
31  4968                 Territory Manager - Mortgage Sales  0.045361   
18    46                              Application Architect  0.082164   
27  4812                                Sales Manager- Clix  0.051447   
43  2464                    Lead Java Developer with Python  0.004507   
44  4806                     Business Development Executive  0.003976   
36  4791          Product Manager – Sales for Lab Equipment  0.032943   
25  3344                     Lead II - Software Engineering  0.062703   
26  1629              Risk Modelling & Analytics Specialist  0.057010   
34  4654                        Product Marketing Associate  0.036534   
35  1656                        Product Marketing Associate  0.036504   
41  1313             Lead Cyber Security- Database Security  0.008848   
33  2876                               Data Science Trainer  0.039902   
28   432                        Associate Product Manager I  0.050956   
37   117                                     Technical Lead  0.029999   
38  4849                              Senior Product Design  0.026010   
39    97                                    Blockchain Lead  0.020473   
40  2567  India Market Unit - Data Science - Utilities -...  0.013028   
42  1847  Technical Research Analyst (Offshore Field Dev...  0.007876   
45  2759      Assistant Vice President (Business Analytics)  0.000000   

      TF-IDF        CV     Final  
1   0.327259  0.333333  0.987731  
2   0.257999  0.282702  0.797545  
0   0.333333  0.024221  0.690887  
6   0.167350  0.258462  0.591529  
7   0.167286  0.167685  0.500624  
3   0.244435  0.000359  0.487941  
5   0.180370  0.121419  0.480535  
12  0.089341  0.280722  0.458135  
13  0.089286  0.280722  0.458025  
14  0.089150  0.280722  0.457754  
4   0.199462  0.004346  0.401694  
15  0.085862  0.221714  0.392202  
9   0.109014  0.129100  0.345699  
10  0.099586  0.120686  0.318501  
8   0.146497  0.009136  0.300525  
24  0.06504

In [62]:
# final2.merge(df, on="JobID")
final_df = df.merge(final2, on="JobID")
final_df

company  \
0                                       Wipro Limited   
1                                        Tech Alchemy   
2                                        Tech Alchemy   
3                                                 UST   
4                                                 UST   
5                                        NICE Systems   
6                                        TMI Group IN   
7   Reserve Bank Information Technology Private Li...   
8                                             Canalys   
9                                                 PwC   
10                                         S&P Global   
11                          JPMorgan Chase Bank, N.A.   
12                                                UBS   
13                       Splash Business Intelligence   
14                                          Cognizant   
15                                              Janes   
16                                        Morningstar   
17                                         S&P Global   
18                                          Cognizant   
19                                           Teradata   
20                                          Accenture   
21                                               Citi   
22                           Innomatics Research Labs   
23                                          Accenture   
24                                         S&P Global   
25                                           BigShyft   
26                                                UST   
27                 Quest Innovative Solutions Pvt Ltd   
28                                      Angel broking   
29                                  forstaffing india   
30                     HDB Financial Services Limited   
31                       Splash Business Intelligence   
32                             Syneos Health Clinical   
33                                             Pfizer   
34                                      Trinity Touch   
35                                               IKEA   
36                                                PwC   
37                          JPMorgan Chase Bank, N.A.   
38                               Saksham Technologies   
39                                         ElectricPe   
40                                       TMI Group IN   
41                         Dimensions HRD Consultants   
42                                           BigShyft   
43                                       TMI Group IN   
44                                         S&P Global   
45                                           BigShyft   

                                       positionName_x  \
0                               Application Architect   
1                                     Blockchain Lead   
2                                      Technical Lead   
3                         Associate Product Manager I   
4         Architect I - Cloud Infrastructure Services   
5             Tech Manager, Cloud operations Engineer   
6   Content writing and market research – Cyber Se...   
7              Lead Cyber Security- Database Security   
8   Market Research Analyst – Cybersecurity and In...   
9                         Advisory_Cyber R&R_TPRM_BLR   
10               Lead Business Intelligence Developer   
11  Know Your Customer - Client Data Analyst - Tea...   
12              Risk Modelling & Analytics Specialist   
13                        Product Marketing Associate   
14                              API Automation Tester   
15  Research Analyst II - EO/IR & Radar Systems (H...   
16                                             Intern   
17  Technical Research Analyst (Offshore Field Dev...   
18  JOB OPENING FOR PERSON WITH DISABILITIES IN CO...   
19                    Lead Java Developer with Python   
20  India Market Unit - Data Science - Utilities -...   
21      Assistant Vice President (Business Analytics)   
22                               Data Science Trainer  

In [63]:
final_df.to_csv("final_df.csv",index=False)
